export const pdfPageTitle = {
  1: "Brief Introduction to MCA 4th Sem Syllabus",
  2: "AI & Machine learning",
  4: "Computer Oriented Optimization",
  6: "Soft Computing",
  8: "Cryptography & Network Security",
  10: "Advance Database",
  12: "Advance OS",
  14: "Multimedia Techniques",
  16: "Web Technology - Advance Java",
  18: "Unix N/W Programming",
  20: "Internet Technologies and Programming",
  22: "Internet of Things",
  24: "Computer Graphics & Multimedia",
  26: "Advance Data Mining",
  28: "Computer Lab – 401 (AI & Machine Learning Lab Assignments)",
  30: "Computer Lab – 402 (Web Technology Lab Assignments)",
  31: "Computer Lab – 402 (Internet of Things Lab Assignments)",
  32: "Computer Lab – 402 (Computer Graphics Lab Assignments)",
  33: "Language Lab – 403 (GD/PI)",
};
